name = "Theme 53"
license = "GPL-3.0"
licenselink = "https://github.com/alamine53/hugo-theme-53/blob/master/LICENSE"
description = "A simple monospaced resume theme for Hugo."
tags = ["blog", "bootstrap", "clean", "minimal", "personal", "responsive", "resume", "simple"]
features = ["bootstrap", "responsive", "simple"]
homepage = "https://github.com/alamine53/hugo-theme-53"
min_version = "0.74.3"

[author]
  name = "Ramzy Al-Amine"
  homepage = "https://ramzyalamine.com/"

[original]
  author = "Olivier Roques"
  homepage = "https://github.com/ojroques"
  repo = "https://github.com/ojroques/hugo-researcher"
